package gui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import controller.Controller;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class LoginPage extends JFrame {
    private static JFrame frame;
    private JPanel basePanel;
    private JLabel logLable;
    private JPanel inputsPanel;
    private JComboBox roleComboBox;
    private JTextField loginTextField;
    private JPasswordField pswdField;
    private JButton loginButton;
    private JButton regButton;
    private Controller controller = new Controller();

    public static void main(String[] args) {
        frame = new JFrame("LoginPage");
        frame.setContentPane(new LoginPage().basePanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public LoginPage() {
        loginButton.addActionListener(e -> {
            String role = (String) roleComboBox.getSelectedItem();
            String login = loginTextField.getText();
            String pswd = pswdField.getText();
            boolean success = true;

            switch (role) {
                case "Studente":
                    try {
                        controller.studenteLogin(login, pswd);
                    } catch (SecurityException se) {
                        JOptionPane.showMessageDialog(basePanel, se.getMessage());
                        success = false;
                    }
                    break;
                case "Docente":
                    try {
                        controller.docenteLogin(login, pswd);
                    } catch (SecurityException se) {
                        JOptionPane.showMessageDialog(basePanel, se.getMessage());
                        success = false;
                    }
                    break;
                case "coordinatore":
                    try {
                        controller.coordinatoreLogin(login, pswd);
                    } catch (SecurityException se) {
                        JOptionPane.showMessageDialog(basePanel, se.getMessage());
                        success = false;
                    }
                    break;
            }
            if (success) {
                JOptionPane.showMessageDialog(basePanel, "Login Success");
                HomePage homePage = new HomePage(frame, controller);
                frame.dispose();
            }
        });

        regButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                RegPage regPage = new RegPage(frame, controller);
                frame.setVisible(false);
            }
        });
    }

    ;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        basePanel = new JPanel();
        basePanel.setLayout(new BorderLayout(0, 0));
        basePanel.setBackground(new Color(-13553359));
        basePanel.setForeground(new Color(-13553359));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-13553359));
        panel1.setForeground(new Color(-13553359));
        basePanel.add(panel1, BorderLayout.NORTH);
        logLable = new JLabel();
        Font logLableFont = this.$$$getFont$$$(null, Font.BOLD, 14, logLable.getFont());
        if (logLableFont != null) logLable.setFont(logLableFont);
        logLable.setForeground(new Color(-2894893));
        logLable.setText("Servizio Università");
        panel1.add(logLable, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        inputsPanel = new JPanel();
        inputsPanel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow"));
        inputsPanel.setBackground(new Color(-13553359));
        inputsPanel.setForeground(new Color(-13553359));
        basePanel.add(inputsPanel, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-2894893));
        label1.setText("Ruolo:");
        CellConstraints cc = new CellConstraints();
        inputsPanel.add(label1, cc.xy(3, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        roleComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Studente");
        defaultComboBoxModel1.addElement("Docente");
        defaultComboBoxModel1.addElement("Coordinatore");
        roleComboBox.setModel(defaultComboBoxModel1);
        inputsPanel.add(roleComboBox, cc.xy(3, 5));
        final JLabel label2 = new JLabel();
        label2.setForeground(new Color(-2894893));
        label2.setText("Email/Username:");
        inputsPanel.add(label2, cc.xy(3, 7, CellConstraints.CENTER, CellConstraints.DEFAULT));
        loginTextField = new JTextField();
        inputsPanel.add(loginTextField, cc.xy(3, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        label3.setForeground(new Color(-2894893));
        label3.setText("Password:");
        inputsPanel.add(label3, cc.xy(3, 11, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        inputsPanel.add(spacer1, cc.xy(5, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        inputsPanel.add(spacer2, cc.xy(1, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        inputsPanel.add(spacer3, cc.xy(3, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        inputsPanel.add(spacer4, cc.xy(3, 15, CellConstraints.DEFAULT, CellConstraints.FILL));
        pswdField = new JPasswordField();
        inputsPanel.add(pswdField, cc.xy(3, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.setBackground(new Color(-13553359));
        panel2.setForeground(new Color(-13553359));
        basePanel.add(panel2, BorderLayout.SOUTH);
        loginButton = new JButton();
        loginButton.setBackground(new Color(-11579569));
        loginButton.setForeground(new Color(-2894893));
        loginButton.setText("Login");
        panel2.add(loginButton);
        regButton = new JButton();
        regButton.setBackground(new Color(-11579569));
        regButton.setForeground(new Color(-2894893));
        regButton.setText("Registra");
        panel2.add(regButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return basePanel;
    }
}

