package gui;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import controller.*;
import controller.exception.DatabaseException;
import controller.exception.UnauthorizedException;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Locale;

public class ManagePage {
    private JFrame frame;
    private JPanel basePanel;
    private JButton accettaButton;
    private JButton rifiutaButton;
    private JComboBox<String> reqComboBox;
    private JLabel oldDateLabel;
    private JLabel newDateLabel;
    private JButton indietroButton;
    private final ChangeOfDateReqService cs = new ChangeOfDateReqService();
    private int selectedId;

    public ManagePage(JFrame callerFrame) {
        frame = new JFrame("Manage");
        frame.setContentPane(basePanel);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        populateRequests();

        indietroButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                callerFrame.setVisible(true);
                frame.dispose();
            }
        });

        rifiutaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                rejectRequest();
            }
        });

        accettaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                acceptRequest();
            }
        });

        reqComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (reqComboBox.getSelectedItem() == null) {
                    oldDateLabel.setText("");
                    newDateLabel.setText("");
                    return;
                }
                selectedId = Integer.parseInt(reqComboBox.getSelectedItem().toString().split(" ")[0]);
                try {
                    oldDateLabel.setText("<html>Vecchio orario:<br>" + cs.getCODROldTimeAndDate(selectedId) + "</html>");
                    newDateLabel.setText("<html>Nuovo orario:<br>" + cs.getCODRNewTimeAndDate(selectedId) + "</html>");
                } catch (UnauthorizedException ue) {
                    JOptionPane.showMessageDialog(frame, ue.getMessage());
                }

            }
        });
    }

    private void populateRequests() {
        List<String> codrs;

        try {
            codrs = cs.getWaitingCODRInfo();
            reqComboBox.setModel(new DefaultComboBoxModel<>(codrs.toArray(new String[0])));
        } catch (UnauthorizedException ue) {
            JOptionPane.showMessageDialog(frame, ue.getMessage());
        } catch (NullPointerException _) {
            JOptionPane.showMessageDialog(frame, "Si e' verificato un errore nel recupero delle richieste.");
        }
    }

    public void acceptRequest() {
        if (reqComboBox.getSelectedItem() == null) return;
        try {
            cs.changeStatusOfCODR(selectedId, true);
            JOptionPane.showMessageDialog(frame, "Richiesta accettata correttamente");
            populateRequests();
            oldDateLabel.setText("");
            newDateLabel.setText("");
        } catch (UnauthorizedException ue) {
            JOptionPane.showMessageDialog(frame, ue.getMessage());
        } catch (DatabaseException de) {
            JOptionPane.showMessageDialog(frame, de.getMessage());
        }
    }

    public void rejectRequest() {
        if (reqComboBox.getSelectedItem() == null) return;
        try {
            cs.changeStatusOfCODR(selectedId, false);
            JOptionPane.showMessageDialog(frame, "Richiesta rifiutata correttamente");
            populateRequests();
            oldDateLabel.setText("");
            newDateLabel.setText("");
        } catch (UnauthorizedException ue) {
            JOptionPane.showMessageDialog(frame, ue.getMessage());
        } catch (DatabaseException de) {
            JOptionPane.showMessageDialog(frame, de.getMessage());
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        basePanel = new JPanel();
        basePanel.setLayout(new BorderLayout(0, 0));
        basePanel.setBackground(new Color(-13553359));
        basePanel.setForeground(new Color(-13553359));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-13553359));
        panel1.setForeground(new Color(-13553359));
        basePanel.add(panel1, BorderLayout.SOUTH);
        rifiutaButton = new JButton();
        rifiutaButton.setBackground(new Color(-5108722));
        rifiutaButton.setEnabled(true);
        rifiutaButton.setForeground(new Color(-2894893));
        rifiutaButton.setText("Rifiuta");
        panel1.add(rifiutaButton, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        accettaButton = new JButton();
        accettaButton.setBackground(new Color(-13925350));
        accettaButton.setForeground(new Color(-2894893));
        accettaButton.setText("Accetta");
        panel1.add(accettaButton, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        indietroButton = new JButton();
        indietroButton.setBackground(new Color(-11579569));
        indietroButton.setEnabled(true);
        indietroButton.setForeground(new Color(-2894893));
        indietroButton.setText("Indietro");
        panel1.add(indietroButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-13553359));
        panel2.setForeground(new Color(-13553359));
        basePanel.add(panel2, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-13553359));
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, 20, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-2894893));
        label1.setText("Gestione richieste spostamento");
        panel2.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:d:grow,top:4dlu:noGrow,center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel3.setBackground(new Color(-13553359));
        panel3.setForeground(new Color(-13553359));
        basePanel.add(panel3, BorderLayout.CENTER);
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-13553359));
        label2.setForeground(new Color(-2894893));
        label2.setText("Seleziona richiesta:");
        CellConstraints cc = new CellConstraints();
        panel3.add(label2, cc.xy(3, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        reqComboBox = new JComboBox();
        reqComboBox.setBackground(new Color(-11579569));
        reqComboBox.setForeground(new Color(-2894893));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        reqComboBox.setModel(defaultComboBoxModel1);
        panel3.add(reqComboBox, cc.xy(3, 5));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel4.setBackground(new Color(-13553359));
        panel4.setForeground(new Color(-13553359));
        panel3.add(panel4, cc.xy(3, 9));
        oldDateLabel = new JLabel();
        oldDateLabel.setBackground(new Color(-13553359));
        oldDateLabel.setForeground(new Color(-2894893));
        oldDateLabel.setText("Label");
        panel4.add(oldDateLabel);
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panel4.add(spacer2);
        newDateLabel = new JLabel();
        newDateLabel.setBackground(new Color(-13553359));
        newDateLabel.setForeground(new Color(-2894893));
        newDateLabel.setText("Label");
        panel4.add(newDateLabel);
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        panel3.add(spacer3, cc.xy(3, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        panel3.add(spacer4, cc.xy(3, 7, CellConstraints.DEFAULT, CellConstraints.FILL));
        final com.intellij.uiDesigner.core.Spacer spacer5 = new com.intellij.uiDesigner.core.Spacer();
        panel3.add(spacer5, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final com.intellij.uiDesigner.core.Spacer spacer6 = new com.intellij.uiDesigner.core.Spacer();
        panel3.add(spacer6, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return basePanel;
    }
}
