package gui;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.MaskFormatter;
import javax.swing.text.StyleContext;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import controller.*;
import controller.exception.DatabaseException;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.time.DayOfWeek;
import java.util.List;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Locale;

public class ReqPage {
    private JFrame frame;
    private JPanel basePanel;
    private JComboBox<String> lezioneComboBox;
    private JComboBox<String> giornoComboBox;
    private JButton confermaButton;
    private JFormattedTextField startFTextField;
    private JFormattedTextField endFTextField;
    private JButton indietroButton;
    private final LectureService ls = new LectureService();
    private final ChangeOfDateReqService cs = new ChangeOfDateReqService();

    public ReqPage(JFrame callerFrame) {
        frame = new JFrame();
        $$$setupUI$$$();
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setContentPane(basePanel);
        frame.pack();
        frame.setVisible(true);
        populateLectures();
        confermaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    if (lezioneComboBox.getSelectedItem() == null) {
                        JOptionPane.showMessageDialog(frame, "Selezionare una lezione");
                        return;
                    }
                    int lectureId = Integer.parseInt(lezioneComboBox.getSelectedItem().toString().split(" ")[0]);
                    LocalTime start = LocalTime.parse(startFTextField.getText(), DateTimeFormatter.ofPattern("HH:mm"));
                    LocalTime end = LocalTime.parse(endFTextField.getText(), DateTimeFormatter.ofPattern("HH:mm"));
                    DayOfWeek dow = DayOfWeek.of(giornoComboBox.getSelectedIndex() + 1);
                    cs.makeChangeOfDateReq(lectureId, dow, start, end);
                    JOptionPane.showMessageDialog(frame, "Richiesta effettuata con successo");
                    callerFrame.setVisible(true);
                    frame.dispose();
                } catch (DateTimeParseException _) {
                    JOptionPane.showMessageDialog(frame, "Inserire un orario valido.");
                } catch (NumberFormatException _) {
                    JOptionPane.showMessageDialog(frame, "Impossibile recuperare l'id della lezione.");
                } catch (RuntimeException re) {
                    JOptionPane.showMessageDialog(frame, re.getMessage());
                } catch (Exception _) {
                    JOptionPane.showMessageDialog(frame, "Si é verificato un errore.");
                }
            }
        });

        indietroButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                callerFrame.setVisible(true);
                frame.dispose();
            }
        });
    }

    private void populateLectures() {
        List<String> lectures;

        try {
            if (!SessionManager.getInstance().isLoggedIn()) {
                JOptionPane.showMessageDialog(frame,
                        "Nessun utente autenticato.",
                        "Errore di Autenticazione",
                        JOptionPane.WARNING_MESSAGE);

                return;
            }
            lectures = ls.getAllByTeacherToString(SessionManager.getInstance().getUserId());
            lezioneComboBox.setModel(new DefaultComboBoxModel<>(lectures.toArray(new String[0])));
        } catch (NullPointerException _) {
            JOptionPane.showMessageDialog(frame, "Si e' verificato un errore nel recupero delle lezioni");
        } catch (DatabaseException de) {
            JOptionPane.showMessageDialog(frame, de.getMessage());
        }
    }

    private void createUIComponents() {
        startFTextField = makeTimeFields();
        endFTextField = makeTimeFields();
    }

    private JFormattedTextField makeTimeFields() {
        try {
            MaskFormatter mask = new MaskFormatter("##:##");
            mask.setPlaceholderCharacter('_');
            return new JFormattedTextField(mask);
        } catch (ParseException _) {
            return new JFormattedTextField();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        basePanel = new JPanel();
        basePanel.setLayout(new BorderLayout(0, 0));
        basePanel.setBackground(new Color(-13553359));
        basePanel.setForeground(new Color(-13553359));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-13553359));
        panel1.setForeground(new Color(-13553359));
        basePanel.add(panel1, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-13553359));
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, 20, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-2894893));
        label1.setText("Richiedi spostamento");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-13553359));
        panel2.setForeground(new Color(-13553359));
        basePanel.add(panel2, BorderLayout.SOUTH);
        confermaButton = new JButton();
        confermaButton.setBackground(new Color(-13925350));
        confermaButton.setForeground(new Color(-2894893));
        confermaButton.setText("Conferma");
        panel2.add(confermaButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        indietroButton = new JButton();
        indietroButton.setBackground(new Color(-11579569));
        indietroButton.setEnabled(true);
        indietroButton.setForeground(new Color(-2894893));
        indietroButton.setText("Indietro");
        panel2.add(indietroButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel3.setBackground(new Color(-13553359));
        panel3.setForeground(new Color(-13553359));
        basePanel.add(panel3, BorderLayout.CENTER);
        final JLabel label2 = new JLabel();
        label2.setForeground(new Color(-2894893));
        label2.setText("Lezione da spostare:");
        CellConstraints cc = new CellConstraints();
        panel3.add(label2, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
        lezioneComboBox = new JComboBox();
        panel3.add(lezioneComboBox, cc.xy(1, 3));
        final JLabel label3 = new JLabel();
        label3.setForeground(new Color(-2894893));
        label3.setText("Sposta al giorno:");
        panel3.add(label3, cc.xy(1, 5, CellConstraints.CENTER, CellConstraints.DEFAULT));
        giornoComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Lunedì");
        defaultComboBoxModel1.addElement("Martedì");
        defaultComboBoxModel1.addElement("Mercoledì");
        defaultComboBoxModel1.addElement("Giovedì");
        defaultComboBoxModel1.addElement("Venerdì");
        giornoComboBox.setModel(defaultComboBoxModel1);
        panel3.add(giornoComboBox, cc.xy(1, 7));
        final JLabel label4 = new JLabel();
        label4.setForeground(new Color(-2894893));
        label4.setText("Nuovo orario inizio:");
        panel3.add(label4, cc.xy(1, 9, CellConstraints.CENTER, CellConstraints.DEFAULT));
        panel3.add(startFTextField, cc.xy(1, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label5 = new JLabel();
        label5.setForeground(new Color(-2894893));
        label5.setText("Nuovo orario fine:");
        panel3.add(label5, cc.xy(1, 13, CellConstraints.CENTER, CellConstraints.DEFAULT));
        panel3.add(endFTextField, cc.xy(1, 15, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return basePanel;
    }
}
